### ISSUE TITLE
More space not need?

### ISSUE THREAD

**Issue by nguyenthenguyen** [ptgamr/soundcloudify#1]
When hide app and then open. Some space not need?
![screenshot from 2015-04-02 163453](https://cloud.githubusercontent.com/assets/8535630/6961653/4f940e7e-d957-11e4-92c7-313795e0abf4.jpg)

**Comment by ptgamr** [comment]
Thanks for reporting this! I'll give a fix soon!

**Comment by ptgamr** [comment]
Fixed in version 1.0.3
