### ISSUE TITLE
[features] add youtube playlist

### ISSUE THREAD

**Issue by truonghoangnguyen** [ptgamr/soundcloudify#11]
I have some play list saved in youtube. like :
https://www.youtube.com/playlist?list=PLFFA46A78F5D9619F

I want to add to play list.

thanks you for your hard work

**Comment by ptgamr** [comment]
Ok, you'll have that very soon :+1: Thanks for your contribution!

**Comment by ptgamr** [comment]
Already implemented. Wait for deployment.

**Comment by truonghoangnguyen** [comment]
+1
thanks
