### ISSUE TITLE
Proposal: Merge forces w/Streamus

### ISSUE THREAD

**Issue by jimthedev** [ptgamr/soundcloudify#18]
Hi there, amazing work. Really enjoying the extension. It seems that there is another extension with the exact same goal. Would it make sense to work together to speed up development. I know the underlying technologies used are different, but figured it couldn't hurt to at least discuss the possibility of a merge to increase development speed on one or both of the projects through a shared library.

See the corresponding thread here: https://github.com/MeoMix/StreamusChromeExtension/issues/573

**Comment by ptgamr** [comment]
If @MeoMix want to... I totally open with this!

**Comment by jimthedev** [comment]
From @MeoMix: "I spoke with him about it. I think we both have a strong desire to continue using the frameworks we've chosen to develop our software with. He has no interest in learning Backbone/Marionette and I have no interest in learning Angular. RIP."

So for now I'll close this and if you guys figure something else out in the future then you can update here.

Cheers.
