### ISSUE TITLE
please commit your ext to github.

### ISSUE THREAD

**Issue by dunghv** [ptgamr/soundcloudify#5]
Since your ext is not avaiable on Chrome Store. 
Better is commit your release version to github. 
User can install it without chrome store. I think.

**Comment by ptgamr** [comment]
Uploaded. You can download it from here: https://github.com/ptgamr/soundcloudify/blob/master/soundcloudify.crx

**Comment by ptgamr** [comment]
Yo, it has come back to Chrome Web Store now :+1:
