### ISSUE TITLE
YouTube is not working 

### ISSUE THREAD

**Issue by puneetsl** [ptgamr/soundcloudify#7]
I don't understand why but YouTube is not working anymore

**Comment by maxkueng** [comment]
Works for me. Listening now.

**Comment by ptgamr** [comment]
Yeap. I'll keep an eye on this!

**Comment by ptgamr** [comment]
Thanks @puneetsl , you're right! Version 1.1.1 will fix the problem :+1:

**Comment by puneetsl** [comment]
:+1: Awesome .. and just wanted to thank you for this nice extension
